### PR TITLE
add support for terraform list and map outputs

### LINKED ISSUE #26: Passing Lists from Terraform outputs
Say we want to pass a list of subnets to a Fargate definition, currently we have to do
```hcl
output "subnet_1" {...}
output "subnet_2" {...}
output "subnet_3" {...}
```

```yml
services:
 - name: example
    vpc_configuration:
        subnets:
            ${terraform.subnet_1}
            ${terraform.subnet_2}
            ${terraform.subnet_3}
```

This means that you have to list them out. Can you do something like:

```hcl
output "app_subnet_ids" {
    value = ["list of subnet ids", ...]
}
```

```yml
services:
 - name: example
    vpc_configuration:
        subnets: ${terraform.app_subnet_ids}
```

And if not, would you consider this as a feature? Being able to pass lists directly from terraform outputs would make certain things really flexible.

My current application is that I'm trying to create a some terraform and deployfish config which can be deployed to any region, which means that we'll have varying numbers of AZs. I'd like to be AZ count agnostic, which we've achieved for our VPC/subnet setup.

### PR DESCRIPTION
**Pull request by acburdine**
closes #26

I ran `nosetests` on the base `test` directory and everything seemed good, not sure if I need to update any of the tests in the `aws` directory.

### CODE REVIEW

**Comment by cmalek** [comment]
Looks clean, thanks.  We've been thinking we need this for a while.  

Could you take a stab at updating the docs for terraform interpolation to say that lists and mappings can be used?   Updating these files are probably sufficent:

```
docs/source/tutorial5.rst
docs/source/yaml.rst
```

**Comment by acburdine** [comment]
@cmalek can do - should I preface it with something like "as of deployfish v0.24.1 (or 0.25.0, idk), lists and maps can now be used"?

**Comment by cmalek** [comment]
You know, we haven't been doing that up till now, so you can just update the docs without referencing version number

**Comment by acburdine** [comment]
@cmalek documentation updated 😄

**Comment by cmalek** [comment]
Thanks!  I've merged your pull request and released it to PyPI as 0.25.0.

**Pull request merged**
