### PR TITLE
PR for target tracking scaling

### PR DESCRIPTION
**Pull request by rv-vmalhotra**
This PR adds in target tracking for auto-scaling feature in deployFish. It has tests written under deployfish/aws/tests/test_ApplicationAutoscaling.py.

### CODE REVIEW

**Comment by cmalek** [comment]
Vikas, did you mean to close this PR?

**Comment by rv-vmalhotra** [comment]
@cmalek I did not mean to close it. I'll reopen the PR. I am not sure what's the process to get this merged though, as in what are the steps required to get it tested in another environment.

**Comment by cmalek** [comment]
Thanks for your submission!  We're reviewing it now.

The process is that we review it, test it out and then we'll merge it into master and publish a new release.

I'll actually have to read up on Target Tracking Scaling.   What I've loved about managing deployfish is that you all tell me about AWS features that I haven't yet heard about!

**Comment by rv-vmalhotra** [comment]
@cmalek I hope you had a good thanksgiving break. I was wondering if you ever got to this PR?

**Comment by cmalek** [comment]
@rv-vmalhotra i'll be closely reviewing this today!

**Comment by cmalek** [comment]
@rv-vmalhotra I think this pull request needs some work.

First, once I applied the pull request, a bunch of pre-existing tests broke.  

Second, I don't think this code should be part of `deployfish.aws.appscaling.ScalingPolicy`  since that is very specifically designed for "traditional" Step Scaling type application autoscaling.  We should be making several different classes here, one for each scaling type, with a factory class that instantiates the proper class based on the specific contents of the `application_scaling` section of the service definition.

My first attempt at how the YAML should work is this:

Step scaling:

```
application_scaling:
  min_capacity: <int>
  max_capacity: <int>
  role_arn: <arn>
  step_scaling:
    - name: <string>
       cpu: <comparison>
       check_every_seconds: <int>
       periods: <int>
       cooldown: <int>
       scale_by: <int>
   - name: <string>
      ...
```

Target tracking scaling (predefined metric)

```
application_scaling:
  min_capacity: <int>
  max_capacity: <int>
  role_arn: <arn>
  target_tracking:
    metric: 'cpu'|'memory'
    target_value: <float>
    scale_in_cooldown: [optional] <int>
    scale_out_cooldown: [optional] <int>
    disable_scale_in: [optional] <bool>
```

Target tracking scaling (custom metric)

```
application_scaling:
  min_capacity: <int>
  max_capacity: <int>
  role_arn: <arn>
  target_tracking:
    metric: 
      name: <string>
      namespace: <string>
      dimensions:
        - name: <string>
          value: <string>
      statistic: <string>
      unit: [optional] <string>
    target_value: <float>
    scale_in_cooldown: [optional] <int>
    scale_out_cooldown: [optional] <int>
    disable_scale_in: [optional] <bool>
```

The factory class rules would be:
 
```
if 'step_scaling' in yml:
   # use existing ScalingPolicy class to manage things; probably rename that to StepScalingPolicy
elif 'target_tracking' in yml:
   if yml['target_tracking']['metric'] in ['cpu', 'memory']:
      # use a new PredefinedTargetTrackingScalingPolicy class to do the work
   else:
      # use a new CustomTargetTrackingScalingPolicy class to do the work
```

In the `CustomTargetTrackingScalingPolicy` case, we'll need to decide how or whether to create the relevant CloudWatch metric.  We make deployfish manage those custom metrics for the Step Scaling functionality; do we make deployfish manage them here also?  Or do we make the user define them themselves?  I would prefer the former, since if the user has to manage the CloudWatch metric themselves, it makes it complicated to create new services since you can't define metrics on services that don't exist yet.

Additionally we'll have to continue to support the existing `application_scaling:` yaml structure (which does not use the `step_scaling` or `target_tracking` dicts) to maintain backwards compatibility with whoever uses such.  Or at least mark such yaml structure as deprecated and then remove it later.

**Pull request merged**
