### PR TITLE
ECS Service Discovery

### PR DESCRIPTION
**Pull request by rv-cohall**
This pull request adds functionality to create an ECS service with service discovery.

https://aws.amazon.com/blogs/aws/amazon-ecs-service-discovery/.

Let me know if you have any suggestions or updates you would like me to make.

### CODE REVIEW

**Comment by cmalek** [comment]
You are awesome!  Thanks for submitting this.  This is something I've been interested in for a while but have not quite figured out how to integrate into our architecture yet.

I have some comments:

*  You need something like `Service.update_scaling()` for service discovery.  I think that currently the code will not purge the service discovery service if in AWS the ECS service has service discovery configured, but our new deployfish.yml has no service discovery set for the service.  I also don't think you can currently update a service discovery service's settings, e.g. change the dns entries, but I might be reading that wrong.
*  Simliarly in `Service.delete()`, I think the code will fail to remove the service discovery service if we removed service discovery from deployfish.yml but the AWS service still has it.   And  I think the code will throw an exception if deployfish.yml does define service discovery, but the AWS service does **not** have it defined.

Quibbles:

* To be consistent with how we do it elsewhere, could you change `set_service_discovery` ecs.py, line 1097 to use the `@service_discovery.setter` decorator to make that method a property setter.  Then you just assign to `self.service_discovery` to set it.  Like so:

```
    @service_discovery.setter
    def service_discovery(self, arn):
        ....
```
* Still in that same method, can you have more than one `registryArn`?  Should you actually be appending there, or should you be doing:

```
    @service_discovery.setter
    def service_discovery(self, arn):
        self.__service_discovery = [{'registryArn': arn}]
```

* ecs.py lines 1199-1202, we probably should be warning people that we're ignoring their service discovery settings when they don't set `network_mode` to "`awsvpc`"
*  I feel like we shouldn't be raising `SystemExit` on ecs.py line 1272.     You might end up with a half configured service that could be hard to clean up on the next run.   Maybe better to just send the message to the user and move on.

**Comment by rv-cohall** [comment]
Thanks for the feedback!

Ok I think I have addressed all of your comments, except for the comment about updating the service. It doesn't look like there is anyway to remove service discovery from an ecs service. The behavior is similar to how load balancers work where you have to delete and recreate the service if you want it removed. I added a comment in the documentation to say that service discovery does not support updates, but requires you to delete and recreate the service.

I updated the delete functionality to always check the existing aws service for the service discovery config. If the service is configured with service discovery then the service discovery will be deleted regardless of whether it exists in the deployfish.yml.

Let me know what you think and if you have any other comments.

**Comment by rv-cohall** [comment]
I also added a dependency for ```requests`` in  ```setup.py```. This was missed in the terraform enterprise pull request.

**Comment by cmalek** [comment]
Thanks!  I'll review your new changes and probably merge and release early next week.

**Pull request merged**
